import type { AuthNode } from "@pg-access/core";
import type { CompileOptions } from "@pg-access/postgres";
import { compile } from "@pg-access/postgres";

export interface TypeOrmMigrationOptions {
  /**
   * Prefix of the class and file name, `PascalCase` like the name
   * `typeorm migration:create` takes. Defaults to `PgAccess`.
   */
  readonly name?: string;
  /** Overrides the clock used for the migration timestamp. Mainly for tests. */
  readonly now?: Date;
}

export interface TypeOrmMigrationStatements {
  /** What `up()` runs, in order. */
  readonly up: readonly string[];
  /** What `down()` runs, in order. */
  readonly down: readonly string[];
}

export interface TypeOrmMigration {
  /** `<timestamp>-<name>.ts`, the same shape `typeorm migration:create` writes. */
  readonly fileName: string;
  /** `<name><timestamp>`; TypeORM reads the migration's timestamp from its last 13 digits. */
  readonly className: string;
  /** The migration's TypeScript source. */
  readonly source: string;
}

const DEFAULT_NAME = "PgAccess";

const HEADER = [
  "// Generated by pg-access.",
  "// Do not hand-edit the policy logic below, change your pg-access",
  "// auth definition instead and regenerate this migration.",
].join("\n");

/**
 * Escapes SQL for a JavaScript template literal. A template literal keeps the
 * compiled SQL multi-line and readable in review, where the single-line
 * double-quoted strings TypeORM's own generator writes would not.
 */
function toTemplateLiteral(sql: string): string {
  return "`" + sql.replace(/[\\`]/g, "\\$&").replace(/\$\{/g, "\\${") + "`";
}

function renderMethod(method: "up" | "down", statements: readonly string[]): string {
  const body = statements
    .map((statement) => `    await queryRunner.query(${toTemplateLiteral(statement)});`)
    .join("\n");

  return [
    `  public async ${method}(queryRunner: QueryRunner): Promise<void> {`,
    ...(body.length > 0 ? [body] : []),
    "  }",
  ].join("\n");
}

/**
 * Wraps already-built SQL statements as a TypeORM migration class. Use this
 * with `planPolicyChanges()`'s `statements` and `down.statements` when
 * reconciling against a live database; `generateTypeOrmMigration()` is the
 * shortcut for the database-free `compile()` path. Writing the file to disk
 * is the caller's job.
 *
 * The class is named `<name><Date.getTime()>`, which is what TypeORM itself
 * requires: its `MigrationExecutor` orders migrations by the 13-digit
 * millisecond timestamp at the end of the class name and refuses to run a
 * class without one.
 */
export function toTypeOrmMigration(
  statements: TypeOrmMigrationStatements,
  options: TypeOrmMigrationOptions = {},
): TypeOrmMigration {
  const name = options.name ?? DEFAULT_NAME;

  if (!/^[A-Za-z_$][\w$]*$/.test(name)) {
    throw new Error(
      `TypeORM migration name must be a valid class name prefix (e.g. "PgAccess"), got ${JSON.stringify(name)}.`,
    );
  }

  const timestamp = (options.now ?? new Date()).getTime();
  const className = `${name}${timestamp}`;

  const source = [
    HEADER,
    "",
    'import type { MigrationInterface, QueryRunner } from "typeorm";',
    "",
    `export class ${className} implements MigrationInterface {`,
    `  name = ${JSON.stringify(className)};`,
    "",
    renderMethod("up", statements.up),
    "",
    renderMethod("down", statements.down),
    "}",
    "",
  ].join("\n");

  return { fileName: `${timestamp}-${name}.ts`, className, source };
}

/**
 * Compiles `auth` into a TypeORM migration class. With no database to diff
 * against, `up()` re-creates every policy and `down()` can only drop them
 * again (see `CompileResult.down`); pass `existingPolicies`, or plan against
 * a live database with `planPolicyChanges()` and `toTypeOrmMigration()`, for
 * a `down()` that restores the previous policies instead.
 */
export function generateTypeOrmMigration(
  auth: AuthNode,
  options: CompileOptions & TypeOrmMigrationOptions = {},
): TypeOrmMigration {
  const { statements, down } = compile(auth, {
    dialect: options.dialect,
    existingPolicies: options.existingPolicies,
  });

  return toTypeOrmMigration(
    { up: statements, down: down.statements },
    { name: options.name, now: options.now },
  );
}
