-- Generated by pg-access.
-- Do not hand-edit the policy logic below, change your pg-access
-- auth definition instead and regenerate this migration.

alter table "projects" enable row level security;

create policy "projects_select"
on "projects"
for select
to "authenticated"
using (
  "user_id" = (select auth.uid())
);

create policy "projects_insert"
on "projects"
for insert
to "authenticated"
with check (
  ((select auth.uid()) is not null and "user_id" = (select auth.uid()))
);

create policy "projects_update"
on "projects"
for update
to "authenticated"
using (
  "user_id" = (select auth.uid())
)
with check (
  "user_id" = (select auth.uid())
);

create policy "projects_delete"
on "projects"
for delete
to "authenticated"
using (
  "user_id" = (select auth.uid())
);
