-- Generated by pg-access.
-- Do not hand-edit the policy logic below, change your pg-access
-- auth definition instead and regenerate this migration.

alter table "profiles" enable row level security;

drop policy if exists "profiles_select" on "profiles";

create policy "profiles_select"
on "profiles"
for select
to "authenticated"
using (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);

drop policy if exists "profiles_insert" on "profiles";

create policy "profiles_insert"
on "profiles"
for insert
to "authenticated"
with check (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);

drop policy if exists "profiles_update" on "profiles";

create policy "profiles_update"
on "profiles"
for update
to "authenticated"
using (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
)
with check (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);

drop policy if exists "profiles_delete" on "profiles";

create policy "profiles_delete"
on "profiles"
for delete
to "authenticated"
using (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);

alter table "posts" enable row level security;

drop policy if exists "posts_select" on "posts";

create policy "posts_select"
on "posts"
for select
to "authenticated"
using (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);

drop policy if exists "posts_insert" on "posts";

create policy "posts_insert"
on "posts"
for insert
to "authenticated"
with check (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);

drop policy if exists "posts_update" on "posts";

create policy "posts_update"
on "posts"
for update
to "authenticated"
using (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
)
with check (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);

drop policy if exists "posts_delete" on "posts";

create policy "posts_delete"
on "posts"
for delete
to "authenticated"
using (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);
