import type { AuthNode } from "@pg-access/core";
import type { CompileOptions } from "../compiler/compiler.js";
import { compile } from "../compiler/compiler.js";

export interface MigrationOptions extends CompileOptions {
  /** Overrides the clock used for the migration timestamp. Mainly for tests. */
  readonly now?: Date;
}

export interface Migration {
  readonly fileName: string;
  readonly sql: string;
}

function pad(value: number, length = 2): string {
  return String(value).padStart(length, "0");
}

/**
 * `yyyyMMddHHmmss` in UTC, the same timestamp format Supabase CLI
 * migrations use. Second-granularity, matching that same convention, means
 * two migrations generated within the same second get the same file name -
 * whoever writes the second one to disk silently overwrites the first.
 * This is inherent to the format (Supabase's own CLI has the identical
 * limitation), not something this function can fix without diverging from
 * the naming convention it's deliberately matching.
 */
function migrationTimestamp(date: Date): string {
  return (
    `${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}` +
    `${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}`
  );
}

const HEADER = [
  "-- Generated by pg-access.",
  "-- Do not hand-edit the policy logic below, change your pg-access",
  "-- auth definition instead and regenerate this migration.",
  "",
  "",
].join("\n");

/**
 * Wraps `compile()`'s output as a named, timestamped migration file body.
 * Writing the file to disk is the caller's job (e.g. the future CLI). This
 * function only decides the file name and content.
 */
export function generateMigration(auth: AuthNode, options: MigrationOptions = {}): Migration {
  const { sql } = compile(auth, {
    dialect: options.dialect,
    existingPolicies: options.existingPolicies,
  });
  const date = options.now ?? new Date();

  return {
    fileName: `${migrationTimestamp(date)}_pg_access.sql`,
    sql: sql.length > 0 ? HEADER + sql : HEADER,
  };
}
