// Generated by pg-access.
// Do not hand-edit the policy logic below, change your pg-access
// auth definition instead and regenerate this migration.

import type { MigrationInterface, QueryRunner } from "typeorm";

export class PgAccess1790515916393 implements MigrationInterface {
  name = "PgAccess1790515916393";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`alter table "notes" enable row level security;`);
    await queryRunner.query(`create policy "notes_select"
on "notes"
for select
to "authenticated"
using (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);`);
    await queryRunner.query(`create policy "notes_insert"
on "notes"
for insert
to "authenticated"
with check (
  "user_id" = (select auth.uid())
);`);
    await queryRunner.query(`create policy "notes_update"
on "notes"
for update
to "authenticated"
using (
  "user_id" = (select auth.uid())
)
with check (
  "user_id" = (select auth.uid())
);`);
    await queryRunner.query(`create policy "notes_delete"
on "notes"
for delete
to "authenticated"
using (
  ("user_id" = (select auth.uid()) or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
);`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`drop policy if exists "notes_delete" on "notes";`);
    await queryRunner.query(`drop policy if exists "notes_insert" on "notes";`);
    await queryRunner.query(`drop policy if exists "notes_select" on "notes";`);
    await queryRunner.query(`drop policy if exists "notes_update" on "notes";`);
    await queryRunner.query(`alter table "notes" disable row level security;`);
  }
}
