import { defineAuth, owner } from "@pg-access/core";
import { describe, expect, it } from "vitest";
import { generateMigration } from "../../src/migrations/generator.js";

describe("generateMigration", () => {
  const auth = defineAuth({ projects: { rows: { select: owner("user_id") } } });

  it("names the file yyyyMMddHHmmss_pg_access.sql, in UTC", () => {
    const migration = generateMigration(auth, { now: new Date("2026-08-19T14:03:07Z") });
    expect(migration.fileName).toBe("20260819140307_pg_access.sql");
  });

  it("includes a header explaining the file is generated", () => {
    const migration = generateMigration(auth, { now: new Date("2026-08-19T14:03:07Z") });
    expect(migration.sql).toContain("Generated by pg-access");
  });

  it("includes the compiled SQL", () => {
    const migration = generateMigration(auth, { now: new Date("2026-08-19T14:03:07Z") });
    expect(migration.sql).toContain('create policy "projects_select"');
  });
});
